FROM node
WORKDIR /client
RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
COPY package*.json ./
COPY pnpm-lock.yaml ./
COPY public ./public
COPY tsconfig.json ./

RUN pnpm fetch
RUN pnpm install

CMD [ "pnpm", "run", "start" ]
EXPOSE 3000