version: "3.3"
services:
  redis:
    image: "redis"
    container_name: "tiddlylogin.redis"
    restart: always
    ports: 
      - "6064:6379"
  db:
    image: "mongo"
    container_name: "tiddlylogin.mongodb"
    restart: always
    ports:
      - "6063:27017"
    volumes:
      - ./mongodb:/data/db
  node:
    # image: node
    build:
      context: .
    container_name: tiddlylogin.server
    restart: always
    ports:
      - 6062:5000
    depends_on:
      - db
      - redis
    links:
      - db:db
      - redis:redis
  react:
    # image: node
    build:
      context: ./client
    container_name: tiddlylogin.react
    restart: always
    environment:
      PORT: 6061
    ports:
      - 6061:6061
    depends_on:
      - node
    links:
      - node
